# Generated by Django 4.0.6 on 2022-09-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAuthor',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('created_dtm', models.DateTimeField()),
                ('username', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'vw_news_filter',
                'managed': False,
            },
        ),
    ]
