# Generated by Django 4.1.2 on 2022-10-05 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_category_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
